Add Java 10 Optional.orElseThrow()
gwtproject/gwt pull request #9843
Opened 2023-07-03 13:55 UTC by niloc132

Partial #9547

2023-07-23 08:36 UTC, vegegoku approved these changes

2023-09-11 09:32 UTC, jnehlmeier requested changes

2023-09-11 09:32 UTC, jnehlmeier commented on user/test/com/google/gwt/emultest/java10/util/OptionalLongTest.java
> +    long value = OptionalLong.of(10).orElseThrow();
Use `10L` here and in the following line. Makes it even more explicit and forces `long` in the method signature of `of()`.

2023-09-13 09:08 UTC, jnehlmeier approved these changes

2023-09-13 12:17 UTC, merged